import type { NextPage } from "next";
import Head from "next/head";
// import Image from 'next/image'
import { Box, Button } from "@chakra-ui/react";
// import styles from '../styles/Home.module.css'
import MonthlyViewService, {
  MonthlyViewData,
} from "../services/MonthlyViewService";
import MonthlyViewTable from "../components/MonthlyViewTable";

interface Props {
  data: MonthlyViewData;
}

const Home: NextPage<Props> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MonthlyViewTable data={data} />
      {/* <Box>
        <Button
          onClick={() => {
            MonthlyViewService.getData(2021, 3).then((res) => {
              console.log(res);
            });
          }}
        >
          Button
        </Button>
      </Box> */}
    </>
  );
};

Home.getInitialProps = async () => {
  const today = new Date();
  const data = await MonthlyViewService.getData(
    today.getFullYear(),
    today.getMonth()
  );
  console.log(data);
  return { data };
};

export default Home;
